export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CREATE_NOTE = 'CREATE_NOTE';
export const VIEW_NOTE = 'VIEW_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const CREATE_BOARD = 'CREATE_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';